### ISSUE TITLE
Dataset has problematic files

### ISSUE THREAD

**Issue by skasewa** [thanard/causal-infogan#2] opened 2019-03-04 17:27 UTC
Hi,

The dataset 

rope_full.tar.gz

has three files that prevent the script from running:

imgs_skipped_10.pkl
imgs_skipped_5.pkl
imgs_skipped_1.pkl

They have some paths hardcoded to your computer, and thus the program crashes. Deleting them seems to work. Are these files essential? If so, consider modifying the code such that it does not use the paths given in these files to look for other files in the dataset.

**Comment by thanard** [comment] 2019-04-15 16:17
Thank you so much, @skasewa, for the feedback. The issue is now fixed.

**Closed** 2019-04-15 16:17 UTC
